# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: ViennaSymphonicLibrary.ViennaAssistant
PackageVersion: 1.1.340
PackageLocale: en-US
Publisher: Vienna Symphonic Library
PublisherUrl: https://www.vsl.co.at
PackageName: Vienna Assistant
PackageUrl: https://www.vsl.info/en/manuals/vienna-assistant/introduction
License: Proprietary
Copyright: © 2002 - 2022 Vienna Symphonic Library GmbH © 2022 The Qt Company Ltd. © 2012 Akos Polster © 2007 Free Software Foundation, Inc. © 2003-2020 Arvid Norberg © 1991, 1999 Free Software Foundation, Inc. © 2015-2017 Lars Pontoppidan
CopyrightUrl: https://www.vsl.info/en/manuals/vienna-assistant/introduction
ShortDescription: Use our new Vienna Assistant to download and install all of your software products and sample libraries.
InstallationNotes: In case you start the application and see neither GUI nor an error message, restart the computer.
Tags:
  - VSL
  - Download manager
  - Sample Library Manager
ManifestType: defaultLocale
ManifestVersion: 1.5.0
